;this file for FamiTone2 library generated by text2data tool

wismm_with_death_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,159,133
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,159,133

@instruments:
	.byte $70 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $70 ;instrument $01
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env6,@env0,@env10
	.byte $00
	.byte $30 ;instrument $04
	.word @env7,@env0,@env9
	.byte $00
	.byte $30 ;instrument $05
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env3,@env0,@env8
	.byte $00
	.byte $b0 ;instrument $08
	.word @env4,@env0,@env0
	.byte $00
	.byte $70 ;instrument $09
	.word @env5,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0a
	.word @env6,@env0,@env9
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c5,$c9,$c6,$c4,$c3,$c4,$c4,$c5,$c4,$c1,$c0,$04,$c0,$00,$03
@env2:
	.byte $c5,$c8,$c7,$c5,$c6,$c6,$c5,$c4,$00,$03
@env3:
	.byte $cb,$cd,$cc,$cb,$c6,$c2,$c0,$00,$06
@env4:
	.byte $ce,$cf,$c8,$c4,$c0,$00,$04
@env5:
	.byte $c1,$c4,$ca,$c9,$c9,$ca,$00,$02
@env6:
	.byte $c4,$ce,$cd,$cc,$cd,$cc,$00,$02
@env7:
	.byte $c5,$cd,$cf,$ce,$c6,$c2,$c0,$00,$06
@env8:
	.byte $80,$00,$00
@env9:
	.byte $b6,$b6,$c0,$00,$02
@env10:
	.byte $b3,$b3,$c0,$00,$02


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $82,$41,$80,$49,$82,$41,$80,$49,$82,$41,$80,$49,$82,$41,$80,$48
	.byte $81
@ref1:
	.byte $82,$3f,$80,$49,$82,$3f,$80,$49,$82,$41,$40,$80,$3e,$82,$41,$40
	.byte $80,$3e
	.byte $ff,$09
	.word @ref0
	.byte $ff,$0a
	.word @ref1
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref4:
	.byte $87,$8a,$58,$85,$56,$8d
@ref5:
	.byte $00,$9d
@ref6:
	.byte $87,$58,$85,$56,$8d
@ref7:
	.byte $00,$9d
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref8:
	.byte $84,$40,$8d,$52,$8d
@ref9:
	.byte $48,$8d,$4a,$8d
@ref10:
	.byte $40,$8d,$52,$8d
@ref11:
	.byte $48,$8d,$4a,$8d
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref12:
	.byte $8c,$17,$17,$8e,$16,$85,$8c,$17,$17,$8e,$16,$85
	.byte $ff,$08
	.word @ref12
	.byte $ff,$08
	.word @ref12
@ref15:
	.byte $8c,$17,$17,$8e,$16,$85,$8c,$17,$17,$8e,$17,$16,$16
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref16:
	.byte $9f
@ref17:
	.byte $9f
@ref18:
	.byte $9f
@ref19:
	.byte $9f
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$07
@song1ch0loop:
@ref20:
	.byte $86,$3a,$fb,$07,$95,$92,$3a,$a5,$3a,$95,$3a,$a5,$3a,$95,$3a,$a5
	.byte $3a,$bd
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref21:
	.byte $86,$40,$95,$92,$3e,$a5,$40,$95,$3e,$a5,$40,$95,$3e,$99,$90,$4f
	.byte $4f,$4f,$52,$8d,$00,$85,$4f,$4f,$52,$8d,$00,$8d
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref22:
	.byte $86,$3a,$95,$48,$a5,$3a,$95,$48,$a5,$3a,$95,$48,$a5,$3a,$95,$48
	.byte $a5
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref23:
	.byte $88,$16,$95,$17,$16,$a1,$16,$95,$17,$16,$a1,$16,$95,$17,$16,$a1
	.byte $16,$95,$17,$16,$a1
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref24:
	.byte $f9,$f9,$8b
	.byte $fd
	.word @song1ch4loop
